# Generated by Django 5.0.6 on 2024-06-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_categories',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Series', 'TV Series'), ('Cartoon', 'Cartoon')], default='Movie', max_length=255),
        ),
    ]
