# Generated by Django 5.0.6 on 2024-06-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='categories',
            field=models.ManyToManyField(default='Action', related_name='movies', to='movies.category'),
        ),
    ]
