# Generated by Django 5.0.6 on 2024-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movies_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='screenshot_urls',
            field=models.JSONField(blank=True, default='list'),
        ),
    ]
