# Generated by Django 5.0.6 on 2024-06-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_usergenrepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('api_id', models.IntegerField(unique=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField()),
                ('number_of_episodes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.series')),
            ],
        ),
    ]
