# Generated by Django 5.0.6 on 2024-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_series_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='screenshot_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
