# Generated by Django 5.0.6 on 2024-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_series_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
