# Generated by Django 5.0.6 on 2024-06-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_series_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_series', to='movies.series'),
        ),
    ]
