# Generated by Django 5.0.6 on 2024-06-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_reviews_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='series',
        ),
    ]
