# Generated by Django 5.0.6 on 2024-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_reviews_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='poster_url',
            field=models.CharField(max_length=400),
        ),
    ]
